[package]
name = "esp-mbedtls"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.84"

[lib]
harness = false

[dependencies]
esp-mbedtls-sys = { path = "../esp-mbedtls-sys" }
log = { version = "0.4.17", default-features = false }
enumset = { version = "1", default-features = false }
embedded-io = { version = "0.6.1" }
embedded-io-async = { version = "0.6.0", optional = true }
esp-hal = { version = "1.0.0", features = ["unstable"], optional = true }
# For malloc/free - using esp-alloc which now provides malloc/free
# esp-wifi dependency removed to avoid version conflicts
esp-alloc = { version = "0.9", optional = true }
cfg-if = "1.0.0"
edge-nal = { version = "0.5.0", optional = true }
critical-section = "1.1.3"
crypto-bigint = { version = "0.5.3", optional = true, default-features = false, features = ["extra-sizes"] }
nb = { version = "1.1.0", optional = true }

[features]
default = ["edge-nal"]
async = ["dep:embedded-io-async"]
esp32 = ["esp-hal/esp32", "esp-alloc", "esp-mbedtls-sys/esp32"]
esp32c3 = ["esp-hal/esp32c3", "esp-alloc", "esp-mbedtls-sys/esp32c3"]
esp32c6 = ["esp-hal/esp32c6", "esp-alloc", "esp-mbedtls-sys/esp32c6"]
esp32s2 = ["esp-hal/esp32s2", "esp-alloc", "esp-mbedtls-sys/esp32s2"]
esp32s3 = ["esp-hal/esp32s3", "esp-alloc", "esp-mbedtls-sys/esp32s3"]

# Implement the traits defined in the latest HEAD of `edge-nal`
edge-nal = ["dep:edge-nal", "async"]

# Enable dependencies related to esp-hal (baremetal)
esp-hal = ["dep:esp-hal", "crypto-bigint", "nb", "esp-alloc"]
